# Generated by Django 3.1.3 on 2020-11-30 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
