# Generated by Django 3.1.3 on 2020-11-30 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20201130_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='size',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
