# Generated by Django 3.1.3 on 2020-11-30 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_paciente_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='species',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
